<?php
class Shape {
    public $name;
    public function __construct($name){
        $this->name = $name;
    }
    public function show (){
        return "I am a shape. My name is $this->name";
    }
}
class Circle extends Shape{
    public int $radius;
    public function __construct($name,$radius)
    {
        parent::__construct($name);
        $this->radius = $radius;
    }
public function calculateArea(){
    return pi() * pow($this->radius,2);
}
public function calculatePerimeter(){
    return pi() * $this->radius * 2;
}
}
class Rectangle extends Shape{
    public $width;
    public $height;
    public function __construct($name,$width, $height)
    {
        parent::__construct($name);
        $this->width = $width;
        $this->height = $height;
    }
    public function calculatePerimeter(){
        return ($this->height + $this->width)*2;
    }
    public function calculateArea(){
        return $this->width * $this->height;
    }
}
class Square extends Rectangle{
    public function __construct($name, $width, $height)
    {
        parent::__construct($name, $width, $height); // TODO: Change the autogenerated stub
    }
    public function calculatePerimeter(){
        return ($this->height + $this->width)*2;
    }
    public function calculateArea(){
        return $this->width * $this->height;
    }
}
$circle = new Circle('Circle1', 3);
echo 'Dien tich hinh tron la :'. $circle->calculateArea().' ';
echo 'Chu vi hinh tron la :'. $circle->calculatePerimeter().'</br>';
$rectangle = new Rectangle('Rectangle', 3,4);
echo 'Dien tich hinh chu nhat la :'. $rectangle->calculateArea(). ' ';
echo 'Chu vi hinh chu nhat la :'. $rectangle->calculatePerimeter().'</br>';
$square = new Square('Square',6,7);
echo 'Dien tich hinh chu nhat la :'. $square->calculateArea(). ' ';
echo 'Chu vi hinh chu nhat la :'. $square->calculatePerimeter();

